Repository Kyo-Pig/Mega-Pig, pull requests merged in 2022-04, with the labels that each got.

#9 Feat/#3 로그인 완성
  Mega-Pig.xcodeproj/project.pbxproj
  Mega-Pig/Assets.xcassets/AppIcon.appiconset/Contents.json
  Mega-Pig/Assets.xcassets/gyo_pig.imageset/Contents.json
  Mega-Pig/Assets.xcassets/gyo_pig.imageset/gyo_pig.jpg
  Mega-Pig/ContentView.swift
  Mega-Pig/Mega_PigApp.swift
  Mega-Pig/login_Views/find_Pw_View.swift
  Mega-Pig/login_Views/login_View.swift
  Mega-Pig/login_Views/signup_email_View.swift
Labels: enhancement, Dodo

#10 Feat/#2 캘린더뷰 & 일일뷰 완성
  Mega-Pig.xcodeproj/project.pbxproj
  Mega-Pig/Assets.xcassets/AccentColor.colorset/Contents.json
  Mega-Pig/Assets.xcassets/temp.imageset/Contents.json
  Mega-Pig/Assets.xcassets/temp.imageset/testImg.heic
  Mega-Pig/CalendarView.swift
  Mega-Pig/DailyView.swift
  Mega-Pig/MainTabView.swift
  Mega-Pig/PieSliceView.swift
  Mega-Pig/TestView.swift
Labels: enhancement, EllyJ

#14 Feat/#13
  Mega-Pig.xcodeproj/project.pbxproj
  Mega-Pig/ContentView.swift
  Mega-Pig/GoogleService-Info.plist
  Mega-Pig/login_Views/login_View.swift
Labels: enhancement, EllyJ

#17 [FIX] Fix Navigation Bar Overlapping Error
  Mega-Pig/CalendarView.swift
  Mega-Pig/ContentView.swift
  Mega-Pig/DailyView.swift
  Mega-Pig/login_Views/login_View.swift
Labels: EllyJ, fix

#18 Feat/#12 MyPage 뷰 추가
  Mega-Pig.xcodeproj/project.pbxproj
  Mega-Pig/Assets.xcassets/userImg.imageset/Contents.json
  Mega-Pig/Assets.xcassets/userImg.imageset/person.crop.circle.svg
  Mega-Pig/ContentView.swift
  Mega-Pig/EditView.swift
  Mega-Pig/MyPageView.swift
  Mega-Pig/TermsOfUseView.swift
Labels: enhancement, EllyJ

#25 Feat merge/#19
  Mega-Pig/MyPageView.swift
  Mega-Pig/TermsOfUseView.swift
Labels: enhancement, EllyJ

#27 Fix/#26
  Mega-Pig/CalendarView.swift
  Mega-Pig/DailyView.swift
  Mega-Pig/MyPageView.swift
Labels: EllyJ, fix
